// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: friend_message.proto

package com.im.domain.pb;

public final class FriendMessageProto {
  private FriendMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * 好友操作类型
   * </pre>
   *
   * Protobuf enum {@code FriendDoType}
   */
  public enum FriendDoType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 同意加好友
     * </pre>
     *
     * <code>AGREE_JOIN_FRIEND = 0;</code>
     */
    AGREE_JOIN_FRIEND(0),
    /**
     * <pre>
     * 拒绝加好友
     * </pre>
     *
     * <code>REFUSE_JOIN_FRIEND = 1;</code>
     */
    REFUSE_JOIN_FRIEND(1),
    /**
     * <pre>
     * 阅后即焚 add v1.1.0
     * </pre>
     *
     * <code>READ_CANCEL = 2;</code>
     */
    READ_CANCEL(2),
    /**
     * <pre>
     * 截屏通知 add v1.1.0
     * </pre>
     *
     * <code>SCREENSHOT = 3;</code>
     */
    SCREENSHOT(3),
    /**
     * <pre>
     * 已读回执开关 add v1.2.0
     * </pre>
     *
     * <code>READ_RECEIPT = 4;</code>
     */
    READ_RECEIPT(4),
    /**
     * <pre>
     * 解除好友关系 v1.6.0 web
     * </pre>
     *
     * <code>RELIEVE_FRIEND = 5;</code>
     */
    RELIEVE_FRIEND(5),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * 同意加好友
     * </pre>
     *
     * <code>AGREE_JOIN_FRIEND = 0;</code>
     */
    public static final int AGREE_JOIN_FRIEND_VALUE = 0;
    /**
     * <pre>
     * 拒绝加好友
     * </pre>
     *
     * <code>REFUSE_JOIN_FRIEND = 1;</code>
     */
    public static final int REFUSE_JOIN_FRIEND_VALUE = 1;
    /**
     * <pre>
     * 阅后即焚 add v1.1.0
     * </pre>
     *
     * <code>READ_CANCEL = 2;</code>
     */
    public static final int READ_CANCEL_VALUE = 2;
    /**
     * <pre>
     * 截屏通知 add v1.1.0
     * </pre>
     *
     * <code>SCREENSHOT = 3;</code>
     */
    public static final int SCREENSHOT_VALUE = 3;
    /**
     * <pre>
     * 已读回执开关 add v1.2.0
     * </pre>
     *
     * <code>READ_RECEIPT = 4;</code>
     */
    public static final int READ_RECEIPT_VALUE = 4;
    /**
     * <pre>
     * 解除好友关系 v1.6.0 web
     * </pre>
     *
     * <code>RELIEVE_FRIEND = 5;</code>
     */
    public static final int RELIEVE_FRIEND_VALUE = 5;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static FriendDoType valueOf(int value) {
      return forNumber(value);
    }

    public static FriendDoType forNumber(int value) {
      switch (value) {
        case 0: return AGREE_JOIN_FRIEND;
        case 1: return REFUSE_JOIN_FRIEND;
        case 2: return READ_CANCEL;
        case 3: return SCREENSHOT;
        case 4: return READ_RECEIPT;
        case 5: return RELIEVE_FRIEND;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<FriendDoType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        FriendDoType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<FriendDoType>() {
            public FriendDoType findValueByNumber(int number) {
              return FriendDoType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.im.domain.pb.FriendMessageProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final FriendDoType[] VALUES = values();

    public static FriendDoType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private FriendDoType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:FriendDoType)
  }

  public interface FriendRecordMsgDtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FriendRecordMsgDto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 发送者ID
     * </pre>
     *
     * <code>optional int64 sendUid = 1;</code>
     */
    long getSendUid();

    /**
     * <pre>
     * 接收者ID
     * </pre>
     *
     * <code>optional int64 receiveUid = 2;</code>
     */
    long getReceiveUid();

    /**
     * <pre>
     * 操作类型
     * </pre>
     *
     * <code>optional .FriendDoType doType = 3;</code>
     */
    int getDoTypeValue();
    /**
     * <pre>
     * 操作类型
     * </pre>
     *
     * <code>optional .FriendDoType doType = 3;</code>
     */
    com.im.domain.pb.FriendMessageProto.FriendDoType getDoType();

    /**
     * <pre>
     * 创建时间
     * </pre>
     *
     * <code>optional int64 createTime = 4;</code>
     */
    long getCreateTime();

    /**
     * <pre>
     * 联系人基本信息(同意/阅后即焚/截屏通知时下发)
     * </pre>
     *
     * <code>optional .ContactsDetailBase contactsDetail = 5;</code>
     */
    boolean hasContactsDetail();
    /**
     * <pre>
     * 联系人基本信息(同意/阅后即焚/截屏通知时下发)
     * </pre>
     *
     * <code>optional .ContactsDetailBase contactsDetail = 5;</code>
     */
    com.im.domain.pb.CommonProto.ContactsDetailBase getContactsDetail();
    /**
     * <pre>
     * 联系人基本信息(同意/阅后即焚/截屏通知时下发)
     * </pre>
     *
     * <code>optional .ContactsDetailBase contactsDetail = 5;</code>
     */
    com.im.domain.pb.CommonProto.ContactsDetailBaseOrBuilder getContactsDetailOrBuilder();

    /**
     * <pre>
     * 是否开启已读回执(隐私开关设置时下发) add v1.2.0
     * </pre>
     *
     * <code>optional bool bfReadReceipt = 6;</code>
     */
    boolean getBfReadReceipt();

    /**
     * <pre>
     * 目标用户id v1.6.0（如，解除好友类型则为接收者的好友id，0-4类型暂不改动）
     * </pre>
     *
     * <code>optional int64 targetUid = 7;</code>
     */
    long getTargetUid();
  }
  /**
   * <pre>
   * 好友请求处理消息
   * </pre>
   *
   * Protobuf type {@code FriendRecordMsgDto}
   */
  public  static final class FriendRecordMsgDto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:FriendRecordMsgDto)
      FriendRecordMsgDtoOrBuilder {
    // Use FriendRecordMsgDto.newBuilder() to construct.
    private FriendRecordMsgDto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FriendRecordMsgDto() {
      sendUid_ = 0L;
      receiveUid_ = 0L;
      doType_ = 0;
      createTime_ = 0L;
      bfReadReceipt_ = false;
      targetUid_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private FriendRecordMsgDto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              sendUid_ = input.readInt64();
              break;
            }
            case 16: {

              receiveUid_ = input.readInt64();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              doType_ = rawValue;
              break;
            }
            case 32: {

              createTime_ = input.readInt64();
              break;
            }
            case 42: {
              com.im.domain.pb.CommonProto.ContactsDetailBase.Builder subBuilder = null;
              if (contactsDetail_ != null) {
                subBuilder = contactsDetail_.toBuilder();
              }
              contactsDetail_ = input.readMessage(com.im.domain.pb.CommonProto.ContactsDetailBase.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(contactsDetail_);
                contactsDetail_ = subBuilder.buildPartial();
              }

              break;
            }
            case 48: {

              bfReadReceipt_ = input.readBool();
              break;
            }
            case 56: {

              targetUid_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.im.domain.pb.FriendMessageProto.internal_static_FriendRecordMsgDto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.im.domain.pb.FriendMessageProto.internal_static_FriendRecordMsgDto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.im.domain.pb.FriendMessageProto.FriendRecordMsgDto.class, com.im.domain.pb.FriendMessageProto.FriendRecordMsgDto.Builder.class);
    }

    public static final int SENDUID_FIELD_NUMBER = 1;
    private long sendUid_;
    /**
     * <pre>
     * 发送者ID
     * </pre>
     *
     * <code>optional int64 sendUid = 1;</code>
     */
    public long getSendUid() {
      return sendUid_;
    }

    public static final int RECEIVEUID_FIELD_NUMBER = 2;
    private long receiveUid_;
    /**
     * <pre>
     * 接收者ID
     * </pre>
     *
     * <code>optional int64 receiveUid = 2;</code>
     */
    public long getReceiveUid() {
      return receiveUid_;
    }

    public static final int DOTYPE_FIELD_NUMBER = 3;
    private int doType_;
    /**
     * <pre>
     * 操作类型
     * </pre>
     *
     * <code>optional .FriendDoType doType = 3;</code>
     */
    public int getDoTypeValue() {
      return doType_;
    }
    /**
     * <pre>
     * 操作类型
     * </pre>
     *
     * <code>optional .FriendDoType doType = 3;</code>
     */
    public com.im.domain.pb.FriendMessageProto.FriendDoType getDoType() {
      com.im.domain.pb.FriendMessageProto.FriendDoType result = com.im.domain.pb.FriendMessageProto.FriendDoType.valueOf(doType_);
      return result == null ? com.im.domain.pb.FriendMessageProto.FriendDoType.UNRECOGNIZED : result;
    }

    public static final int CREATETIME_FIELD_NUMBER = 4;
    private long createTime_;
    /**
     * <pre>
     * 创建时间
     * </pre>
     *
     * <code>optional int64 createTime = 4;</code>
     */
    public long getCreateTime() {
      return createTime_;
    }

    public static final int CONTACTSDETAIL_FIELD_NUMBER = 5;
    private com.im.domain.pb.CommonProto.ContactsDetailBase contactsDetail_;
    /**
     * <pre>
     * 联系人基本信息(同意/阅后即焚/截屏通知时下发)
     * </pre>
     *
     * <code>optional .ContactsDetailBase contactsDetail = 5;</code>
     */
    public boolean hasContactsDetail() {
      return contactsDetail_ != null;
    }
    /**
     * <pre>
     * 联系人基本信息(同意/阅后即焚/截屏通知时下发)
     * </pre>
     *
     * <code>optional .ContactsDetailBase contactsDetail = 5;</code>
     */
    public com.im.domain.pb.CommonProto.ContactsDetailBase getContactsDetail() {
      return contactsDetail_ == null ? com.im.domain.pb.CommonProto.ContactsDetailBase.getDefaultInstance() : contactsDetail_;
    }
    /**
     * <pre>
     * 联系人基本信息(同意/阅后即焚/截屏通知时下发)
     * </pre>
     *
     * <code>optional .ContactsDetailBase contactsDetail = 5;</code>
     */
    public com.im.domain.pb.CommonProto.ContactsDetailBaseOrBuilder getContactsDetailOrBuilder() {
      return getContactsDetail();
    }

    public static final int BFREADRECEIPT_FIELD_NUMBER = 6;
    private boolean bfReadReceipt_;
    /**
     * <pre>
     * 是否开启已读回执(隐私开关设置时下发) add v1.2.0
     * </pre>
     *
     * <code>optional bool bfReadReceipt = 6;</code>
     */
    public boolean getBfReadReceipt() {
      return bfReadReceipt_;
    }

    public static final int TARGETUID_FIELD_NUMBER = 7;
    private long targetUid_;
    /**
     * <pre>
     * 目标用户id v1.6.0（如，解除好友类型则为接收者的好友id，0-4类型暂不改动）
     * </pre>
     *
     * <code>optional int64 targetUid = 7;</code>
     */
    public long getTargetUid() {
      return targetUid_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (sendUid_ != 0L) {
        output.writeInt64(1, sendUid_);
      }
      if (receiveUid_ != 0L) {
        output.writeInt64(2, receiveUid_);
      }
      if (doType_ != com.im.domain.pb.FriendMessageProto.FriendDoType.AGREE_JOIN_FRIEND.getNumber()) {
        output.writeEnum(3, doType_);
      }
      if (createTime_ != 0L) {
        output.writeInt64(4, createTime_);
      }
      if (contactsDetail_ != null) {
        output.writeMessage(5, getContactsDetail());
      }
      if (bfReadReceipt_ != false) {
        output.writeBool(6, bfReadReceipt_);
      }
      if (targetUid_ != 0L) {
        output.writeInt64(7, targetUid_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (sendUid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, sendUid_);
      }
      if (receiveUid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, receiveUid_);
      }
      if (doType_ != com.im.domain.pb.FriendMessageProto.FriendDoType.AGREE_JOIN_FRIEND.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, doType_);
      }
      if (createTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, createTime_);
      }
      if (contactsDetail_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getContactsDetail());
      }
      if (bfReadReceipt_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, bfReadReceipt_);
      }
      if (targetUid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, targetUid_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.im.domain.pb.FriendMessageProto.FriendRecordMsgDto)) {
        return super.equals(obj);
      }
      com.im.domain.pb.FriendMessageProto.FriendRecordMsgDto other = (com.im.domain.pb.FriendMessageProto.FriendRecordMsgDto) obj;

      boolean result = true;
      result = result && (getSendUid()
          == other.getSendUid());
      result = result && (getReceiveUid()
          == other.getReceiveUid());
      result = result && doType_ == other.doType_;
      result = result && (getCreateTime()
          == other.getCreateTime());
      result = result && (hasContactsDetail() == other.hasContactsDetail());
      if (hasContactsDetail()) {
        result = result && getContactsDetail()
            .equals(other.getContactsDetail());
      }
      result = result && (getBfReadReceipt()
          == other.getBfReadReceipt());
      result = result && (getTargetUid()
          == other.getTargetUid());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + SENDUID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSendUid());
      hash = (37 * hash) + RECEIVEUID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getReceiveUid());
      hash = (37 * hash) + DOTYPE_FIELD_NUMBER;
      hash = (53 * hash) + doType_;
      hash = (37 * hash) + CREATETIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCreateTime());
      if (hasContactsDetail()) {
        hash = (37 * hash) + CONTACTSDETAIL_FIELD_NUMBER;
        hash = (53 * hash) + getContactsDetail().hashCode();
      }
      hash = (37 * hash) + BFREADRECEIPT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getBfReadReceipt());
      hash = (37 * hash) + TARGETUID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTargetUid());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.im.domain.pb.FriendMessageProto.FriendRecordMsgDto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.im.domain.pb.FriendMessageProto.FriendRecordMsgDto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.im.domain.pb.FriendMessageProto.FriendRecordMsgDto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.im.domain.pb.FriendMessageProto.FriendRecordMsgDto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.im.domain.pb.FriendMessageProto.FriendRecordMsgDto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.im.domain.pb.FriendMessageProto.FriendRecordMsgDto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.im.domain.pb.FriendMessageProto.FriendRecordMsgDto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.im.domain.pb.FriendMessageProto.FriendRecordMsgDto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.im.domain.pb.FriendMessageProto.FriendRecordMsgDto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.im.domain.pb.FriendMessageProto.FriendRecordMsgDto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.im.domain.pb.FriendMessageProto.FriendRecordMsgDto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 好友请求处理消息
     * </pre>
     *
     * Protobuf type {@code FriendRecordMsgDto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FriendRecordMsgDto)
        com.im.domain.pb.FriendMessageProto.FriendRecordMsgDtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.im.domain.pb.FriendMessageProto.internal_static_FriendRecordMsgDto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.im.domain.pb.FriendMessageProto.internal_static_FriendRecordMsgDto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.im.domain.pb.FriendMessageProto.FriendRecordMsgDto.class, com.im.domain.pb.FriendMessageProto.FriendRecordMsgDto.Builder.class);
      }

      // Construct using com.im.domain.pb.FriendMessageProto.FriendRecordMsgDto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        sendUid_ = 0L;

        receiveUid_ = 0L;

        doType_ = 0;

        createTime_ = 0L;

        if (contactsDetailBuilder_ == null) {
          contactsDetail_ = null;
        } else {
          contactsDetail_ = null;
          contactsDetailBuilder_ = null;
        }
        bfReadReceipt_ = false;

        targetUid_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.im.domain.pb.FriendMessageProto.internal_static_FriendRecordMsgDto_descriptor;
      }

      public com.im.domain.pb.FriendMessageProto.FriendRecordMsgDto getDefaultInstanceForType() {
        return com.im.domain.pb.FriendMessageProto.FriendRecordMsgDto.getDefaultInstance();
      }

      public com.im.domain.pb.FriendMessageProto.FriendRecordMsgDto build() {
        com.im.domain.pb.FriendMessageProto.FriendRecordMsgDto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.im.domain.pb.FriendMessageProto.FriendRecordMsgDto buildPartial() {
        com.im.domain.pb.FriendMessageProto.FriendRecordMsgDto result = new com.im.domain.pb.FriendMessageProto.FriendRecordMsgDto(this);
        result.sendUid_ = sendUid_;
        result.receiveUid_ = receiveUid_;
        result.doType_ = doType_;
        result.createTime_ = createTime_;
        if (contactsDetailBuilder_ == null) {
          result.contactsDetail_ = contactsDetail_;
        } else {
          result.contactsDetail_ = contactsDetailBuilder_.build();
        }
        result.bfReadReceipt_ = bfReadReceipt_;
        result.targetUid_ = targetUid_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.im.domain.pb.FriendMessageProto.FriendRecordMsgDto) {
          return mergeFrom((com.im.domain.pb.FriendMessageProto.FriendRecordMsgDto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.im.domain.pb.FriendMessageProto.FriendRecordMsgDto other) {
        if (other == com.im.domain.pb.FriendMessageProto.FriendRecordMsgDto.getDefaultInstance()) return this;
        if (other.getSendUid() != 0L) {
          setSendUid(other.getSendUid());
        }
        if (other.getReceiveUid() != 0L) {
          setReceiveUid(other.getReceiveUid());
        }
        if (other.doType_ != 0) {
          setDoTypeValue(other.getDoTypeValue());
        }
        if (other.getCreateTime() != 0L) {
          setCreateTime(other.getCreateTime());
        }
        if (other.hasContactsDetail()) {
          mergeContactsDetail(other.getContactsDetail());
        }
        if (other.getBfReadReceipt() != false) {
          setBfReadReceipt(other.getBfReadReceipt());
        }
        if (other.getTargetUid() != 0L) {
          setTargetUid(other.getTargetUid());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.im.domain.pb.FriendMessageProto.FriendRecordMsgDto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.im.domain.pb.FriendMessageProto.FriendRecordMsgDto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long sendUid_ ;
      /**
       * <pre>
       * 发送者ID
       * </pre>
       *
       * <code>optional int64 sendUid = 1;</code>
       */
      public long getSendUid() {
        return sendUid_;
      }
      /**
       * <pre>
       * 发送者ID
       * </pre>
       *
       * <code>optional int64 sendUid = 1;</code>
       */
      public Builder setSendUid(long value) {
        
        sendUid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 发送者ID
       * </pre>
       *
       * <code>optional int64 sendUid = 1;</code>
       */
      public Builder clearSendUid() {
        
        sendUid_ = 0L;
        onChanged();
        return this;
      }

      private long receiveUid_ ;
      /**
       * <pre>
       * 接收者ID
       * </pre>
       *
       * <code>optional int64 receiveUid = 2;</code>
       */
      public long getReceiveUid() {
        return receiveUid_;
      }
      /**
       * <pre>
       * 接收者ID
       * </pre>
       *
       * <code>optional int64 receiveUid = 2;</code>
       */
      public Builder setReceiveUid(long value) {
        
        receiveUid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 接收者ID
       * </pre>
       *
       * <code>optional int64 receiveUid = 2;</code>
       */
      public Builder clearReceiveUid() {
        
        receiveUid_ = 0L;
        onChanged();
        return this;
      }

      private int doType_ = 0;
      /**
       * <pre>
       * 操作类型
       * </pre>
       *
       * <code>optional .FriendDoType doType = 3;</code>
       */
      public int getDoTypeValue() {
        return doType_;
      }
      /**
       * <pre>
       * 操作类型
       * </pre>
       *
       * <code>optional .FriendDoType doType = 3;</code>
       */
      public Builder setDoTypeValue(int value) {
        doType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 操作类型
       * </pre>
       *
       * <code>optional .FriendDoType doType = 3;</code>
       */
      public com.im.domain.pb.FriendMessageProto.FriendDoType getDoType() {
        com.im.domain.pb.FriendMessageProto.FriendDoType result = com.im.domain.pb.FriendMessageProto.FriendDoType.valueOf(doType_);
        return result == null ? com.im.domain.pb.FriendMessageProto.FriendDoType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 操作类型
       * </pre>
       *
       * <code>optional .FriendDoType doType = 3;</code>
       */
      public Builder setDoType(com.im.domain.pb.FriendMessageProto.FriendDoType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        doType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 操作类型
       * </pre>
       *
       * <code>optional .FriendDoType doType = 3;</code>
       */
      public Builder clearDoType() {
        
        doType_ = 0;
        onChanged();
        return this;
      }

      private long createTime_ ;
      /**
       * <pre>
       * 创建时间
       * </pre>
       *
       * <code>optional int64 createTime = 4;</code>
       */
      public long getCreateTime() {
        return createTime_;
      }
      /**
       * <pre>
       * 创建时间
       * </pre>
       *
       * <code>optional int64 createTime = 4;</code>
       */
      public Builder setCreateTime(long value) {
        
        createTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 创建时间
       * </pre>
       *
       * <code>optional int64 createTime = 4;</code>
       */
      public Builder clearCreateTime() {
        
        createTime_ = 0L;
        onChanged();
        return this;
      }

      private com.im.domain.pb.CommonProto.ContactsDetailBase contactsDetail_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.im.domain.pb.CommonProto.ContactsDetailBase, com.im.domain.pb.CommonProto.ContactsDetailBase.Builder, com.im.domain.pb.CommonProto.ContactsDetailBaseOrBuilder> contactsDetailBuilder_;
      /**
       * <pre>
       * 联系人基本信息(同意/阅后即焚/截屏通知时下发)
       * </pre>
       *
       * <code>optional .ContactsDetailBase contactsDetail = 5;</code>
       */
      public boolean hasContactsDetail() {
        return contactsDetailBuilder_ != null || contactsDetail_ != null;
      }
      /**
       * <pre>
       * 联系人基本信息(同意/阅后即焚/截屏通知时下发)
       * </pre>
       *
       * <code>optional .ContactsDetailBase contactsDetail = 5;</code>
       */
      public com.im.domain.pb.CommonProto.ContactsDetailBase getContactsDetail() {
        if (contactsDetailBuilder_ == null) {
          return contactsDetail_ == null ? com.im.domain.pb.CommonProto.ContactsDetailBase.getDefaultInstance() : contactsDetail_;
        } else {
          return contactsDetailBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * 联系人基本信息(同意/阅后即焚/截屏通知时下发)
       * </pre>
       *
       * <code>optional .ContactsDetailBase contactsDetail = 5;</code>
       */
      public Builder setContactsDetail(com.im.domain.pb.CommonProto.ContactsDetailBase value) {
        if (contactsDetailBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          contactsDetail_ = value;
          onChanged();
        } else {
          contactsDetailBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * 联系人基本信息(同意/阅后即焚/截屏通知时下发)
       * </pre>
       *
       * <code>optional .ContactsDetailBase contactsDetail = 5;</code>
       */
      public Builder setContactsDetail(
          com.im.domain.pb.CommonProto.ContactsDetailBase.Builder builderForValue) {
        if (contactsDetailBuilder_ == null) {
          contactsDetail_ = builderForValue.build();
          onChanged();
        } else {
          contactsDetailBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * 联系人基本信息(同意/阅后即焚/截屏通知时下发)
       * </pre>
       *
       * <code>optional .ContactsDetailBase contactsDetail = 5;</code>
       */
      public Builder mergeContactsDetail(com.im.domain.pb.CommonProto.ContactsDetailBase value) {
        if (contactsDetailBuilder_ == null) {
          if (contactsDetail_ != null) {
            contactsDetail_ =
              com.im.domain.pb.CommonProto.ContactsDetailBase.newBuilder(contactsDetail_).mergeFrom(value).buildPartial();
          } else {
            contactsDetail_ = value;
          }
          onChanged();
        } else {
          contactsDetailBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * 联系人基本信息(同意/阅后即焚/截屏通知时下发)
       * </pre>
       *
       * <code>optional .ContactsDetailBase contactsDetail = 5;</code>
       */
      public Builder clearContactsDetail() {
        if (contactsDetailBuilder_ == null) {
          contactsDetail_ = null;
          onChanged();
        } else {
          contactsDetail_ = null;
          contactsDetailBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * 联系人基本信息(同意/阅后即焚/截屏通知时下发)
       * </pre>
       *
       * <code>optional .ContactsDetailBase contactsDetail = 5;</code>
       */
      public com.im.domain.pb.CommonProto.ContactsDetailBase.Builder getContactsDetailBuilder() {
        
        onChanged();
        return getContactsDetailFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * 联系人基本信息(同意/阅后即焚/截屏通知时下发)
       * </pre>
       *
       * <code>optional .ContactsDetailBase contactsDetail = 5;</code>
       */
      public com.im.domain.pb.CommonProto.ContactsDetailBaseOrBuilder getContactsDetailOrBuilder() {
        if (contactsDetailBuilder_ != null) {
          return contactsDetailBuilder_.getMessageOrBuilder();
        } else {
          return contactsDetail_ == null ?
              com.im.domain.pb.CommonProto.ContactsDetailBase.getDefaultInstance() : contactsDetail_;
        }
      }
      /**
       * <pre>
       * 联系人基本信息(同意/阅后即焚/截屏通知时下发)
       * </pre>
       *
       * <code>optional .ContactsDetailBase contactsDetail = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.im.domain.pb.CommonProto.ContactsDetailBase, com.im.domain.pb.CommonProto.ContactsDetailBase.Builder, com.im.domain.pb.CommonProto.ContactsDetailBaseOrBuilder> 
          getContactsDetailFieldBuilder() {
        if (contactsDetailBuilder_ == null) {
          contactsDetailBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.im.domain.pb.CommonProto.ContactsDetailBase, com.im.domain.pb.CommonProto.ContactsDetailBase.Builder, com.im.domain.pb.CommonProto.ContactsDetailBaseOrBuilder>(
                  getContactsDetail(),
                  getParentForChildren(),
                  isClean());
          contactsDetail_ = null;
        }
        return contactsDetailBuilder_;
      }

      private boolean bfReadReceipt_ ;
      /**
       * <pre>
       * 是否开启已读回执(隐私开关设置时下发) add v1.2.0
       * </pre>
       *
       * <code>optional bool bfReadReceipt = 6;</code>
       */
      public boolean getBfReadReceipt() {
        return bfReadReceipt_;
      }
      /**
       * <pre>
       * 是否开启已读回执(隐私开关设置时下发) add v1.2.0
       * </pre>
       *
       * <code>optional bool bfReadReceipt = 6;</code>
       */
      public Builder setBfReadReceipt(boolean value) {
        
        bfReadReceipt_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 是否开启已读回执(隐私开关设置时下发) add v1.2.0
       * </pre>
       *
       * <code>optional bool bfReadReceipt = 6;</code>
       */
      public Builder clearBfReadReceipt() {
        
        bfReadReceipt_ = false;
        onChanged();
        return this;
      }

      private long targetUid_ ;
      /**
       * <pre>
       * 目标用户id v1.6.0（如，解除好友类型则为接收者的好友id，0-4类型暂不改动）
       * </pre>
       *
       * <code>optional int64 targetUid = 7;</code>
       */
      public long getTargetUid() {
        return targetUid_;
      }
      /**
       * <pre>
       * 目标用户id v1.6.0（如，解除好友类型则为接收者的好友id，0-4类型暂不改动）
       * </pre>
       *
       * <code>optional int64 targetUid = 7;</code>
       */
      public Builder setTargetUid(long value) {
        
        targetUid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 目标用户id v1.6.0（如，解除好友类型则为接收者的好友id，0-4类型暂不改动）
       * </pre>
       *
       * <code>optional int64 targetUid = 7;</code>
       */
      public Builder clearTargetUid() {
        
        targetUid_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:FriendRecordMsgDto)
    }

    // @@protoc_insertion_point(class_scope:FriendRecordMsgDto)
    private static final com.im.domain.pb.FriendMessageProto.FriendRecordMsgDto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.im.domain.pb.FriendMessageProto.FriendRecordMsgDto();
    }

    public static com.im.domain.pb.FriendMessageProto.FriendRecordMsgDto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FriendRecordMsgDto>
        PARSER = new com.google.protobuf.AbstractParser<FriendRecordMsgDto>() {
      public FriendRecordMsgDto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new FriendRecordMsgDto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FriendRecordMsgDto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FriendRecordMsgDto> getParserForType() {
      return PARSER;
    }

    public com.im.domain.pb.FriendMessageProto.FriendRecordMsgDto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FriendRecordMsgDto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FriendRecordMsgDto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024friend_message.proto\032\014common.proto\"\303\001\n" +
      "\022FriendRecordMsgDto\022\017\n\007sendUid\030\001 \001(\003\022\022\n\n" +
      "receiveUid\030\002 \001(\003\022\035\n\006doType\030\003 \001(\0162\r.Frien" +
      "dDoType\022\022\n\ncreateTime\030\004 \001(\003\022+\n\016contactsD" +
      "etail\030\005 \001(\0132\023.ContactsDetailBase\022\025\n\rbfRe" +
      "adReceipt\030\006 \001(\010\022\021\n\ttargetUid\030\007 \001(\003*\204\001\n\014F" +
      "riendDoType\022\025\n\021AGREE_JOIN_FRIEND\020\000\022\026\n\022RE" +
      "FUSE_JOIN_FRIEND\020\001\022\017\n\013READ_CANCEL\020\002\022\016\n\nS" +
      "CREENSHOT\020\003\022\020\n\014READ_RECEIPT\020\004\022\022\n\016RELIEVE" +
      "_FRIEND\020\005B&\n\020com.im.domain.pbB\022FriendMes",
      "sageProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.im.domain.pb.CommonProto.getDescriptor(),
        }, assigner);
    internal_static_FriendRecordMsgDto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_FriendRecordMsgDto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FriendRecordMsgDto_descriptor,
        new java.lang.String[] { "SendUid", "ReceiveUid", "DoType", "CreateTime", "ContactsDetail", "BfReadReceipt", "TargetUid", });
    com.im.domain.pb.CommonProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
